language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services: mongodb

install:
  - pip install tornado
  - pip install git+https://github.com/mongodb/mongo-python-driver.git

script: "python setup.py test"

branches:
  only:
    - master
