language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
services: mongodb
script: "python setup.py test"

# Futures were introduced in Python 3.2 in the `concurrent.futures` package.
# This package has also been backported to older versions of Python and can be
# installed with `pip install futures`. Tornado 3 uses concurrent.futures if
# available; otherwise it will use a compatible class defined in
# tornado.concurrent. We want to test all cases: with and without the 'futures'
# package installed in Python < 3.2, as well as Python >= 3.2.

env:
  - FUTURES=yes
  - FUTURES=no
  - TORNADO=3
  - TORNADO=4
matrix:
  exclude:
    - python: "3.3"
      env: FUTURES=yes
    - python: "3.4"
      env: FUTURES=yes
    # Tornado 3 lacks a fix for test errors related to GC and unclosed sockets.
    - python: "3.4"
      env: TORNADO=3
    # Tornado 4 doesn't use concurrent.futures.
    - env: TORNADO=4
      env: FUTURES=yes
before_install:
  # Wait a little longer for MongoDB to start on slow test machines.
  - sleep 5
before_script:
  - if [[ "$FUTURES" == "yes" ]]; then pip install futures; fi
  - if [[ "$TORNADO" == "3" ]]; then pip install 'tornado>=3'; fi
  - if [[ "$TORNADO" == "4" ]]; then pip install https://github.com/tornadoweb/tornado/archive/v4.0.0b1.zip; fi

branches:
  only:
    - master
    - stable
